### ISSUE TITLE
[1.17.1] Will not load

### ISSUE THREAD

**Issue by ProsperCraft** [someaddons/limitedchunks#1]
**Mod file version**
limitedchunks-1.17.1-2.0.jar

**Describe the bug**
Will not load on client or server when added to my TownCraft THREE pack.

https://gist.github.com/ProsperCraft/808b3b1d1fea809b2d49c582810f5eb0

**Comment by someaddons** [comment]
funny when you do not use mixins and dont have a mixin file, but an entry pointing to it it crashes.
Anways fixed in v2.1
