### ISSUE TITLE
[Bug]: branch version/1.16 outdated

### ISSUE THREAD

**Issue by Paradis4432** [someaddons/limitedchunks#12]
### Describe the bug you're experiencing

seems to have gotten updates https://github.com/someaddons/limitedchunks/issues/2
but not pushed to the 1.16 branch

thanks!

### Reproducability

none

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs

no logs, just missing update

**Comment by someaddons** [comment]
Dont have that old branch around anymore, would recommend backporting from a newer branch instead
