### ISSUE TITLE
Can't exclude mods?

### ISSUE THREAD

**Issue by massacring** [someaddons/limitedchunks#13]
I'm probably doing or understanding something wrong, but this mod seems to still be unloading chunks that are loaded by mods in the excluded list in the config.
Here's the config:
```
{
  "chunkunloadnoplayer": {
    "desc:": "How many minutes chunkloaded chunks stay active after player logging out. default:10, min 0, max 2000",
    "chunkunloadnoplayer": 10
  },
  "debugLog": {
    "desc:": "Print log messages for which chunk tickets are unloaded where. Default: false",
    "debugLog": false
  },
  "excludedtickets": {
    "desc:": "List of excluded ticket/chunkload types, these are mod-specific. : e.g. format :  [\"mekanism\", \"player\"]",
    "excludedtickets": ["mekanism", "fluxnetworks"]
  }
}
```
To be clear, what I want is to keep the chunks being loaded by these mods from being unloaded (preferably at all, but at least while the player is online).

**Comment by someaddons** [comment]
the mod by default does not unload stuff while the player is still online, only after they log off. If you want to see exactly what it unloaded I recommend turning on the debug logging

**Comment by someaddons** [comment]
btw to exclude the mods you need to find the actual name the mod uses for its tickets

**Comment by massacring** [comment]
> the mod by default does not unload stuff while the player is still online, only after they log off. If you want to see exactly what it unloaded I recommend turning on the debug logging

I didn't check with the debug but it was definitely your mod causing the issue, since it disappeared after I removed the mod.

> btw to exclude the mods you need to find the actual name the mod uses for its tickets

Why does the example say "mekanism" if that doesn't work?

**Comment by someaddons** [comment]
its an example for the format, you ofc need to figure out the ID's you want to exclude first.
Causation and correlation are two different things, my mod does not unload chunks before the player who loaded them logs out, but that also means they don't auto-load on start.
