### ISSUE TITLE
Server crashes when players disconnect

### ISSUE THREAD

**Issue by ghost** [someaddons/limitedchunks#2]
**Mod file version**
limitedchunks 1.10

**Describe the bug**
The server crashes when a player disconnects

**To Reproduce**
1. Disconnect from the server (tough because it only happens sometimes)

**Expected behavior**
I expect the server not to crash when a player disconnects

**Screenshots**
From the end of the latest.log
![image](https://user-images.githubusercontent.com/82549089/143732559-a9eb35b6-5901-425a-b5b6-4004a8a8b854.png)

From the crash report
![image](https://user-images.githubusercontent.com/82549089/143732571-b19d4858-79f1-445d-be89-32414bff81c3.png)

The crash report itself
[crash-2021-11-27_23.40.52-server.txt](https://github.com/someaddons/limitedchunks/files/7612946/crash-2021-11-27_23.40.52-server.txt)

**Comment by someaddons** [comment]
fixed in 2.1
