### ISSUE TITLE
1.16.5 - FTB Chunks loads remain loaded?

### ISSUE THREAD

**Issue by nanonestor** [someaddons/limitedchunks#3]
**Mod file version**
The exact name of the mod file version.
limitedchunks-2.1.jar
Forge 36.2.22

**Describe the bug**
FTB Chunks chunkloads remain loaded despite mod being present and set to 10 minute disable time.

(Using Admin/OP to remove the FTB load does remove the load)

**To Reproduce**
-Load a 36.2.22 server world with FTB Chunks / teams 
-log in and claim/load a chunk using FTB chunks
-be amazed as the chunk remains actively loaded forever

**Expected behavior**
Is this expected? FTB Chunks config does also have a config setting to allow loading while players are offline or not. Setting was tried both true and false with no change.

**Screenshots**
Let me know if there is any further information that can be provided to help?

**Comment by someaddons** [comment]
its possible that another mod reloads the chunks or readds the tickets, I'd suggest to turn on the debug config option in limited chunks to see the log messages when it removes a chunk ticket.
