### ISSUE TITLE
Chunk Loaders (1.18.2)

### ISSUE THREAD

**Issue by HacoKavanah** [someaddons/limitedchunks#4]
### Describe the bug you're experiencing

This is not a bug, I was just wondering if this affects chunk loaders from mods such as tech reborn and kibe utilities.

And does the player in question need to log out or just be out of the specific chunk for the 10minutes time?

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

-

**Comment by HacoKavanah** [comment]
Was testing this and was successful, the mod indeed stops all chunkloaders at the 10min mark. How do I use the excluded tickets thing to make them work again? The log listed it as ticket:forced, but following your example and putting forced into the config only crashes the game.

**Comment by someaddons** [comment]
The idea of the mod is that chunkloaders stop working after X minutes after the player logs off, by default it is 10 minutes. You can increase that time in the config

**Comment by someaddons** [comment]
fabric version wasnt really working btw, fixed in 2.5
