### ISSUE TITLE
[Crash]: Randomly crashed 

### ISSUE THREAD

**Issue by xR4YM0ND** [someaddons/limitedchunks#5]
### Describe the bug you're experiencing

I wasnt there when it happend ^^

im running 1.18.2 but i can not add that tag to the version drop down menu

[Crash Report](https://gist.github.com/SpigotDE/0e6ff09683710eef1be4d047456a20ef)

### Reproducability

idk

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://gist.github.com/SpigotDE/abe3870b087b7e8a687dc7fed8ac2343

**Comment by xR4YM0ND** [comment]
happend again after some minutes passed by

**Comment by someaddons** [comment]
Yep turns out mixins we're accidently client-only. Fixed in 2.5
