### ISSUE TITLE
[Bug]: Fabric 1.18.2 naming conflict with carpet

### ISSUE THREAD

**Issue by DadoIrie** [someaddons/limitedchunks#6]
### Describe the bug you're experiencing

`Method overwrite conflict for getTicketsByPosition in limitedchunks.mixins.json:ChunkTicketManagerAccessorMixin from mod limitedchunks, previously written by carpet.mixins.DistanceManager_scarpetMixin. Skipping method.`

a naming conflict of the getTicketsByPosition method or simply incompatible with carpet? 

### Reproducability

simply load limitedchunks with carpet and right before preparing spawn area you'll see the console log ;)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

https://mclo.gs/oo6okaF

**Comment by someaddons** [comment]
not an actual problem, they just have the same thing there, only an issue if it crashes

**Comment by DadoIrie** [comment]
> not an actual problem, they just have the same thing there, only an issue if it crashes

it doesn't seem that it is the same feature tho and skipping method because of a naming conflict pretty much means one feature is turned off forcefully ... 
![image](https://user-images.githubusercontent.com/61109153/184498187-110cdbb1-7329-4a98-8520-7073dec0bb26.png)

> This mod serves as a middle-way between no chunkloading at all and chunkloading forever, by unloading these loaded chunks after a configured time after the corresponding player logged off.

*and this is the main reason why I am interested in this mod so if this can get fixed it is much appreciated*
