### ISSUE TITLE
[Bug]: Possible chunk-loading issue

### ISSUE THREAD

**Issue by Sunconure11** [someaddons/limitedchunks#7]
### Describe the bug you're experiencing

Doing some exploring, I ran into this error. I'm wondering if it is connected here, or any other mod dealing with chunks

### Reproducability

1. Muck around
2. Find out
https://gist.github.com/Sunconure11/5fca9900af67fba9e1b48ad645f9f60f

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://pastebin.com/J5i28UwL

**Comment by someaddons** [comment]
nah thats some issue regarding entities, an area this mod does not touch at all
