### ISSUE TITLE
[Bug]: Potentially at fault, incompatibility with Lithium?

### ISSUE THREAD

**Issue by ereese99** [someaddons/limitedchunks#9]
### Describe the bug you're experiencing

Server crashing when loading in chunks

### Reproducability

Just load in chunks 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/ereese99/18889f95b8a0df4c238de6df4b44bc3b

**Comment by someaddons** [comment]
unrelated to limited chunk loading, this mod simply observes and removes chunk tickets
